### ISSUE TITLE
`demuxer-cache-state` / `mpv_node`

### ISSUE THREAD

**Issue by yaymukund** [ParadoxSpiral/mpv-rs#12]
First of all, thanks for maintaining this lib. It's been great, and excited to see you're working on it again.

Second, would you accept a PR that implements `mpv_node`? If so, I'm happy to take a crack at it.  I was going to begin by trying to `impl GetData`, but I am not sure how it should be represented in Rust. I haven't written something like this before, so any advice or direction would be appreciated.

Thanks for reading :)

**Comment by yaymukund** [comment]
I opened #13 which is a very rough sketch of this.

**Comment by ParadoxSpiral** [comment]
I left some comments on the PR :)

**Comment by ParadoxSpiral** [comment]
Fixed by #13
