### ISSUE TITLE
Playing the previous item in a playlist doesn't work

### ISSUE THREAD

**Issue by eetumos** [ParadoxSpiral/mpv-rs#17]
I couldn't get `Mpv::playlist_previous_weak()` and `Mpv::playlist_previous_force()` to work while `Mpv::playlist_next_weak()` and `Mpv::playlist_next_force()` work just fine. I am able to play the previous item by using the command `playlist-prev` instead of `playlist-previous` which is used [here](https://github.com/ParadoxSpiral/libmpv-rs/blob/07daa5ecff74157fea5a5ebc2771730fa65d28be/src/mpv.rs#L669) and [here](https://github.com/ParadoxSpiral/libmpv-rs/blob/07daa5ecff74157fea5a5ebc2771730fa65d28be/src/mpv.rs#L674).

[This section](https://mpv.io/manual/master/#command-interface-playlist-prev) in the mpv manual describes `playlist-prev`.

**Comment by ParadoxSpiral** [comment]
Fixed in [this](https://github.com/ParadoxSpiral/libmpv-rs/commit/e307ea70ecbe9e17c1523fe5f7eae2d27f18acf2) commit which is in the 2.0.1 release.

Thanks for your report!
