### ISSUE TITLE
[QUESTION] Is this repo maintained

### ISSUE THREAD

**Issue by sudipghimire533** [ParadoxSpiral/mpv-rs#23]
I was thinking of using this crate but seems like author is not being able to give time to for it's maintenance. Can this be used? I mean if this repo is in eye of maintainers?

**Comment by tramhao** [comment]
I have the same question because I need a small fix to use it.

**Comment by ParadoxSpiral** [comment]
Yes, I will address all Issues & PRs. Not sure if I will develop new features myself
