### ISSUE TITLE
libmpv version issue after upgrading to mpv `0.35.0`

### ISSUE THREAD

**Issue by sirno** [ParadoxSpiral/mpv-rs#27]
Hi unfortunately libmpv stops working after upgrading mpv to version `0.35.0` on mac os using brew

```Error: VersionMismatch { linked: 65644, loaded: 131072 }```

My guess would be that this is related to the pregenerated bindings, but who knows...

**Comment by sirno** [comment]
The error was thrown by libmpv-rs based on the specified library version. Upgrading the bindings for libmpv 2.0 resolved the issue. #28

**Comment by maulik9898** [comment]
I am getting this error while linking `target/debug/mpv-rs: error while loading shared libraries: libmpv.so.2: cannot open shared object file: No such file or directory`

**Comment by sirno** [comment]
@maulik9898 this is likely an unrelated issue. your error message indicates that the shared library cannot be found where it is looking for it.

**Comment by maulik9898** [comment]
Yes, I was able to solve this by adding PATH to LD_LIBRARY_PATH.
