### ISSUE TITLE
`VersionMismatch` after mpv v0.29.1

### ISSUE THREAD

**Issue by yaymukund** [ParadoxSpiral/mpv-rs#5]
```bash
$ cargo run --example events_simple --
   Compiling mpv-sys v2.0.0 (mpv-rs/mpv-sys)
   Compiling mpv v0.0.1 (mpv-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.94s
     Running `target/debug/examples/events_simple`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VersionMismatch { linked: 65636, loaded: 65637 }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

$ mpv -V
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.1
```
If I remove the version mismatch check, everything works as expected, for what that's worth :)

**Comment by yaymukund** [comment]
I was able to get this working by bumping the minor version 100 → 101:

https://github.com/ParadoxSpiral/mpv-rs/blob/6ae89d74340db3280711d844395358ec7ffed614/src/lib.rs#L53

Here's the relevant release notes, for your convenience: https://github.com/mpv-player/mpv/releases/tag/v0.29.1

**Comment by ParadoxSpiral** [comment]
Thanks for the heads up!
I've been meaning to implement the new render API after I removed the opengl_callback one some time ago, but haven't gotten around to working on this crate.
As far as I can see (https://github.com/mpv-player/mpv/blob/master/DOCS/client-api-changes.rst#api-changes) just increasing the version should be fine for now.

EDIT: I'll update the crate on monday or tuesday.

**Comment by yaymukund** [comment]
@ParadoxSpiral thank you for your work on this crate (: 

I bumped the version locally so I could continue my work. Today, I've been doing basic stuff (play URL, change volume, queue track, seek) and it seems to work as expected.
