### ISSUE TITLE
Implement std::error::Error for mpv::Error

### ISSUE THREAD

**Issue by theduke** [ParadoxSpiral/mpv-rs#8]

**Comment by theduke** [comment]
This `todo!()` here is somewhat ... suboptimal:

https://github.com/ParadoxSpiral/mpv-rs/commit/77537550a0f945a8b712af93c5cf6d6a48d013a0#diff-c0500a66570aa12fe7ea7ca77e2542cfR41

;)

**Comment by ParadoxSpiral** [comment]
Oof, thanks for looking over it. I had intended to use the debug print.
